const val PAGE_COUNT = 100
const val PROCESS_COUNT = 10
const val FRAME_COUNT = 30
const val LOCALITY_BASE_CHANCE = 20
const val LOCALITY_GAIN = 2
const val LOCALITY_MINIMAL_LENGTH = 2
const val LOCALITY_MAXIMAL_LENGTH = 25